"""second third

Revision ID: 38699296ccd5
Revises: 4ce4c9a8eebe
Create Date: 2022-05-20 15:14:54.224463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38699296ccd5'
down_revision = '4ce4c9a8eebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('picture', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
