"""second migration

Revision ID: e6370f86de6d
Revises: 20ca3b6b8c9e
Create Date: 2022-05-18 10:20:20.755286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6370f86de6d'
down_revision = '20ca3b6b8c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
